services:
  api:
    image: dihasi/kauth
    container_name: api
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
        postgres:
          condition: service_healthy
        redis:
            condition: service_healthy
    networks:
      - public
      - api

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy
      - api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - api
      - public
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
    api:
        internal: true
    proxy:
        internal: true
    public:
        internal: false